#!/bin/bash

#Parameters
PRODUCT_HOME=/Library/__PRODUCT__/__VERSION__

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

#Add application shortcut to /usr/local/bin
ln -sf ${PRODUCT_HOME}/iosdk /usr/local/bin/iosdk
ln -sf ${PRODUCT_HOME}/wsk /usr/local/bin/wsk
echo "Post installation process finished"
